/**
 * ReflectionCard — V7 tool-history reflection card (PR-L).
 *
 * Renders a single reflection generated by T1 (in-turn) or T2 (end-of-turn)
 * for the Yeaft chat. Shows a loading state while `status === 'pending'`
 * and parses the markdown sections produced by `reflection-prompt.js` into
 * a 5-section card.
 *
 * Section headings the prompt always emits (in order):
 *   ## What was attempted
 *   ## Key findings
 *   ## Direction check
 *   ## Suggested next direction
 *   ## Tool execution log
 *
 * "Direction check" is expanded by default; the others collapse for
 * scannability. No horizontal dividers — spacing handles separation per
 * the Yeaft UI Design Rules in CLAUDE.md.
 */
export default {
  name: 'ReflectionCard',
  props: {
    card: { type: Object, required: true },
  },
  data() {
    return {
      // Keys correspond to section titles.
      expanded: {
        'What was attempted': false,
        'Key findings': false,
        'Direction check': true,
        'Suggested next direction': false,
        'Tool execution log': false,
      },
    };
  },
  computed: {
    isPending() {
      return this.card && this.card.status === 'pending';
    },
    isError() {
      return this.card && this.card.status === 'error';
    },
    triggerLabel() {
      return this.card.trigger === 't1' ? 'In-turn reflection' : 'End-of-turn reflection';
    },
    sections() {
      const content = this.card && this.card.content || '';
      return parseSections(content);
    },
  },
  methods: {
    toggle(title) {
      this.expanded = { ...this.expanded, [title]: !this.expanded[title] };
    },
  },
  template: `
    <div class="reflection-card" :class="{ 'is-pending': isPending, 'is-error': isError }">
      <div class="reflection-head">
        <span class="reflection-icon">↻</span>
        <span class="reflection-label">{{ triggerLabel }}</span>
        <span v-if="card.toolCount" class="reflection-meta">{{ card.toolCount }} tool calls</span>
        <span v-if="card.durationMs" class="reflection-meta">{{ card.durationMs }}ms</span>
      </div>

      <div v-if="isPending" class="reflection-pending">
        <span class="reflection-spinner"></span>
        Reflecting on the last batch of tool calls…
      </div>

      <div v-else-if="isError" class="reflection-error">
        Reflection failed: {{ card.error || 'unknown error' }}
      </div>

      <div v-else class="reflection-body">
        <div
          v-for="sec in sections"
          :key="sec.title"
          class="reflection-section"
        >
          <button class="reflection-section-toggle" @click="toggle(sec.title)">
            <span class="reflection-caret">{{ expanded[sec.title] ? '▾' : '▸' }}</span>
            {{ sec.title }}
          </button>
          <div v-if="expanded[sec.title]" class="reflection-section-body">{{ sec.body }}</div>
        </div>
      </div>
    </div>
  `,
};

/**
 * Split the reflection markdown by '##' headings into ordered sections.
 * @param {string} md
 * @returns {Array<{ title: string, body: string }>}
 */
function parseSections(md) {
  const out = [];
  if (typeof md !== 'string' || !md.trim()) return out;
  const lines = md.split('\n');
  let current = null;
  for (const line of lines) {
    const m = /^##\s+(.+?)\s*$/.exec(line);
    if (m) {
      if (current) out.push(current);
      current = { title: m[1], body: '' };
    } else if (current) {
      current.body += (current.body ? '\n' : '') + line;
    }
  }
  if (current) out.push(current);
  for (const s of out) s.body = s.body.trim();
  return out;
}

export { parseSections };
