/**
 * VpAvatar — VP head circle.
 *
 * Visual stack (back → front):
 *   1. Zodiac-inspired gradient disk (background of `.vp-avatar`, inline `:style`)
 *   2. Illustrated SVG portrait — `/assets/avatars/<vpId>.svg` when known
 *      (transparent background, so the palette colour shows through any
 *      empty pixels). Pre-generated by `scripts/generate-avatars.mjs`.
 *   3. Motif glyph + display initial — rendered ONLY when the illustration
 *      is unknown or fails to load, so fallback avatars are still distinct.
 *   4. Status dot (online/busy) OR typing badge (task-708) — pinned to
 *      bottom-right, never both at once (status wins).
 *
 * The illustration layer is the new piece. Everything else is preserved
 * so the avatar never breaks: an unknown vpId, a 404 SVG, or a corrupt
 * file all fall through to the original letter-on-disc look.
 *
 * Props:
 *   vpId      — required; lookup key into vp store + filename of SVG
 *   size      — px diameter (default 20). 14 chip / 20 bubble / 24 sidebar / 32 detail / 48 hero
 *   status    — 'online' | 'busy' | null
 *   typing    — bool. See task-708 — bottom-right typing badge.
 *   ariaLabel — optional; falls back to displayName
 */
import { useVpStore } from '../stores/vp.js';

// Hard-coded list of vpIds we ship illustrated avatars for. Must match
// the ENTRIES array in scripts/generate-avatars.mjs. Anything outside
// this set falls back to the letter render — never hits a 404.
const KNOWN_AVATAR_IDS = new Set([
  // Original 12 (engineering / design / science / security / business).
  'ada', 'alan', 'alice', 'dieter', 'grace', 'ken',
  'linus', 'margaret', 'martin', 'norman', 'shannon', 'steve',
  // Expansion 20 (philosophy / psychology / strategy / history /
  // investing / business / writing / science / arts).
  'kongzi', 'socrates', 'nietzsche', 'kahneman', 'jung',
  'sunzi', 'clausewitz', 'simaqian', 'harari',
  'buffett', 'munger', 'dalio', 'bezos', 'drucker',
  'luxun', 'sudongpo', 'borges', 'einstein',
  'kubrick', 'miyazaki',
]);

export default {
  name: 'VpAvatar',
  props: {
    vpId: { type: String, required: true },
    size: { type: Number, default: 20 },
    status: { type: String, default: null },
    typing: { type: Boolean, default: false },
    ariaLabel: { type: String, default: '' },
  },
  template: `
    <span
      class="vp-avatar"
      :class="{ 'is-busy': status === 'busy', 'is-online': status === 'online', 'is-typing': typing && !status }"
      :style="avatarStyle"
      :aria-label="ariaLabel || displayName"
      role="img"
    >
      <img
        v-if="avatarUrl"
        class="vp-avatar-img"
        :src="avatarUrl"
        alt=""
        draggable="false"
        @error="onImgError"
      />
      <span v-else class="vp-avatar-letter" :data-motif="motifKey" aria-hidden="true">
        <span class="vp-avatar-motif-glyph">{{ motifGlyph }}</span>
        <span class="vp-avatar-initial">{{ initial }}</span>
      </span>
      <span
        v-if="status === 'online' || status === 'busy'"
        class="vp-avatar-status-dot"
        :class="'status-' + status"
      ></span>
      <span
        v-else-if="typing"
        class="vp-avatar-typing-badge"
        aria-hidden="true"
      >
        <span class="vp-avatar-typing-dot"></span>
        <span class="vp-avatar-typing-dot"></span>
        <span class="vp-avatar-typing-dot"></span>
      </span>
    </span>
  `,
  setup(props) {
    const store = useVpStore();
    const initial = Vue.computed(() => store.vpInitial(props.vpId));
    const displayName = Vue.computed(() => store.vpLabel(props.vpId));
    const motif = Vue.computed(() => {
      const fn = store.vpAvatarMotif;
      return typeof fn === 'function'
        ? fn(props.vpId)
        : {
          key: 'rat',
          glyph: 'R',
          background: 'linear-gradient(135deg, #174EA6 0%, #0B2F6B 100%)',
          foreground: '#FFFFFF',
        };
    });
    const color = Vue.computed(() => {
      const fn = store.vpColor;
      return typeof fn === 'function' ? fn(props.vpId) : motif.value.background;
    });
    const motifKey = Vue.computed(() => motif.value.key);
    const motifGlyph = Vue.computed(() => motif.value.glyph);
    const motifColor = Vue.computed(() => motif.value.foreground);
    // imgFailed flips to true once the <img> emits an error event for
    // this mount, forcing the letter fallback. It does NOT reset on its
    // own — the Vue.watch below is load-bearing: when this component
    // is reused for a different vpId (Vue list-key reuse), the watch
    // clears the flag so the new VP gets a fresh shot at loading.
    const imgFailed = Vue.ref(false);
    const avatarUrl = Vue.computed(() => {
      if (imgFailed.value) return null;
      const id = props.vpId;
      if (!id || !KNOWN_AVATAR_IDS.has(id)) return null;
      return `/assets/avatars/${id}.svg`;
    });
    function onImgError() {
      imgFailed.value = true;
    }
    // Load-bearing: see the imgFailed comment above. Without this,
    // a stale "this VP's SVG broke once" decision would leak into the
    // next VP that lands in this component slot.
    Vue.watch(() => props.vpId, () => { imgFailed.value = false; });
    const avatarStyle = Vue.computed(() => ({
      width: props.size + 'px',
      height: props.size + 'px',
      background: color.value,
      color: motifColor.value,
      fontSize: Math.max(13, Math.round(props.size * 0.58)) + 'px',
    }));
    return {
      initial,
      displayName,
      avatarStyle,
      avatarUrl,
      motifKey,
      motifGlyph,
      onImgError,
    };
  },
};
