/**
 * memory/summary-store.js — DESIGN-H2-AMS §3.
 *
 * `summary.md` is a bounded, per-scope prose digest derived from all
 * segments in that scope. Resident AMS layer = concatenation of all
 * relevant scope summaries. Regenerated by Dream after segments change.
 *
 * Layout:
 *   ~/.yeaft/memory/<scope>/summary.md
 *
 * Format: plain prose, optionally prefixed with a one-line metadata
 * header `<!-- updatedAt: ISO -->`. No required schema beyond non-empty
 * text.
 */

import {
  readFileSync, writeFileSync, existsSync, mkdirSync, renameSync,
} from 'node:fs';
import { join, dirname } from 'node:path';

/**
 * @param {string} memoryRoot
 * @param {string} scope
 * @returns {string}
 */
export function summaryPath(memoryRoot, scope) {
  return join(memoryRoot, scope, 'summary.md');
}

/**
 * Read summary text for a scope (empty string if missing).
 *
 * @param {string} memoryRoot
 * @param {string} scope
 * @returns {string}
 */
export function readSummary(memoryRoot, scope) {
  const p = summaryPath(memoryRoot, scope);
  if (!existsSync(p)) return '';
  return stripHeader(readFileSync(p, 'utf8')).trim();
}

/**
 * Atomic write summary text. Empty string = wipe content but keep file.
 *
 * @param {string} memoryRoot
 * @param {string} scope
 * @param {string} text
 */
export function writeSummary(memoryRoot, scope, text) {
  const p = summaryPath(memoryRoot, scope);
  mkdirSync(dirname(p), { recursive: true });
  const header = `<!-- updatedAt: ${new Date().toISOString()} -->\n`;
  const body = (text || '').trim();
  const final = body ? `${header}${body}\n` : header;
  const tmp = `${p}.tmp`;
  writeFileSync(tmp, final, 'utf8');
  renameSync(tmp, p);
}

function stripHeader(text) {
  return text.replace(/^<!--[^>]*-->\s*/m, '');
}
